name: Test

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        include:
          - php: 8.1
            wp: latest
          - php: 8.0
            wp: latest
          - php: 7.4
            wp: latest

    name: PHP ${{ matrix.php }} / WP ${{ matrix.wp }} Test
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, mysqli
          init-valuse: post_max_size=256M, short_open_tag=On
          coverage: none

      - name: Check PHP Version
        run: php -v

      - name: Install phpunit global
        run: |
          composer global require "phpunit/phpunit=5.7.*|6.*.*|7.*.*"
          phpunit --version

      - name: Cache composer packages
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist

      - name: Install WP Tests
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wp }} true

      - name: Build
        run: |
          bash ./bin/build.sh

      - name: phpunit tests
        run: |
          phpunit
          WP_MULTISITE=1 phpunit

  lint:
    runs-on:  ubuntu-latest
    name: PHP lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring, intl #optional, setup extensions
          ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
          coverage: xdebug #optional, setup coverage driver

      - name: Check PHP Version
        run: php -v

      - name: Cache composer packages
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist

      - name: phpcs tests
        run: composer phpcs
